apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: mysql:5.7
      args:
        - "--default-authentication-plugin=mysql_native_password"
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_DATABASE
          value: "mydb"
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_PASSWORD
          value: "admin"
        - name: MYSQL_ROOT_PASSWORD
          value: "admin"
      volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      livenessProbe:
        exec:
          command:
            - "/bin/sh"
            - "-c"
            - "mysqladmin ping -h 127.0.0.1"
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
  volumes:
    - name: mysql-data
      emptyDir: {}
